### ISSUE TITLE
Fix analysis empty `tests`

### ISSUE THREAD

**Issue by garrettmaring** [engi-network/cli#31]
The [unsolved](https://github.com/garrettmaring/with-jest-app/tree/unsolved) branch of a new `--with-jest` NextJs app has 6 passing tests and 1 failed one.

However, running `engi analyse --branch=unsolved https://github.com/garrettmaring/with-jest-app | tee with-jest-app-analysis.json` shows an empty `tests` array.

**Comment by garrettmaring** [comment]
Output JSON of `npm test -- --json`:

```
{"numFailedTestSuites":1,"numFailedTests":1,"numPassedTestSuites":6,"numPassedTests":7,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":7,"numTotalTests":8,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":1,"total":1,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1696959142600,"success":false,"testResults":[{"assertionResults":[{"ancestorTitles":[],"duration":45,"failureDetails":[],"failureMessages":[],"fullName":"App Router: Works with Client Components","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"App Router: Works with Client Components"}],"endTime":1696959143974,"message":"","name":"/Users/g/Developer/with-jest-app/app/client/page.test.tsx","startTime":1696959143149,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":[],"duration":54,"failureDetails":[],"failureMessages":[],"fullName":"App Router: Works with Server Components","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"App Router: Works with Server Components"}],"endTime":1696959143984,"message":"","name":"/Users/g/Developer/with-jest-app/app/rsc/page.test.tsx","startTime":1696959143145,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":[],"duration":54,"failureDetails":[],"failureMessages":[],"fullName":"App Router: Works with dynamic route segments","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"App Router: Works with dynamic route segments"}],"endTime":1696959143992,"message":"","name":"/Users/g/Developer/with-jest-app/app/blog/[slug]/page.test.tsx","startTime":1696959143147,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":[],"duration":99,"failureDetails":[],"failureMessages":[],"fullName":"renders homepage unchanged","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"renders homepage unchanged"}],"endTime":1696959144076,"message":"","name":"/Users/g/Developer/with-jest-app/__tests__/snapshot.tsx","startTime":1696959143151,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":[],"duration":119,"failureDetails":[],"failureMessages":[],"fullName":"App Router: Works with Client Components (React State)","invocations":1,"location":null,"numPassingAsserts":2,"retryReasons":[],"status":"passed","title":"App Router: Works with Client Components (React State)"}],"endTime":1696959144081,"message":"","name":"/Users/g/Developer/with-jest-app/app/component.test.tsx","startTime":1696959143152,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":["Home"],"duration":120,"failureDetails":[],"failureMessages":[],"fullName":"Home renders a heading","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"renders a heading"}],"endTime":1696959144104,"message":"","name":"/Users/g/Developer/with-jest-app/__tests__/index.test.tsx","startTime":1696959143149,"status":"passed","summary":""},{"assertionResults":[{"ancestorTitles":["Button"],"duration":2568,"failureDetails":[],"failureMessages":[],"fullName":"Button renders the primary button","invocations":1,"location":null,"numPassingAsserts":1,"retryReasons":[],"status":"passed","title":"renders the primary button"},{"ancestorTitles":["Button"],"duration":1196,"failureDetails":[{"matcherResult":{"pass":false,"message":"Expected Icon to match design. See temp/primary-button-icon-comp.png. There is a 12.11% difference.\nhttp://localhost:6006/iframe.html?viewMode=story&id=button--icon"},"message":"Expected Icon to match design. See temp/primary-button-icon-comp.png. There is a 12.11% difference.\nhttp://localhost:6006/iframe.html?viewMode=story&id=button--icon"}],"failureMessages":["Error: Expected Icon to match design. See temp/primary-button-icon-comp.png. There is a 12.11% difference.\nhttp://localhost:6006/iframe.html?viewMode=story&id=button--icon\n    at Object.toMatchDesign (/Users/g/Developer/with-jest-app/stories/Button.test.tsx:24:40)\n    at Promise.then.completed (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/run.js:316:40)\n    at _runTest (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/g/Developer/with-jest-app/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/g/Developer/with-jest-app/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/g/Developer/with-jest-app/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/g/Developer/with-jest-app/node_modules/jest-runner/build/testWorker.js:106:12)"],"fullName":"Button renders the primary button with icon","invocations":1,"location":null,"numPassingAsserts":0,"retryReasons":[],"status":"failed","title":"renders the primary button with icon"}],"endTime":1696959147582,"message":"\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mButton › renders the primary button with icon\u001b[39m\u001b[22m\n\n    Expected Icon to match design. See temp/primary-button-icon-comp.png. There is a 12.11% difference.\n    http://localhost:6006/iframe.html?viewMode=story&id=button--icon\n\u001b[2m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 22 |\u001b[39m     }\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 23 |\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[2m\u001b[39m\u001b[90m 24 |\u001b[39m     \u001b[36mawait\u001b[39m expect(buttonIconDesignTest)\u001b[33m.\u001b[39mtoMatchDesign()\u001b[33m;\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m    |\u001b[39m                                        \u001b[31m\u001b[1m^\u001b[22m\u001b[2m\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 25 |\u001b[39m   })\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 26 |\u001b[39m })\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 27 |\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.toMatchDesign (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/Button.test.tsx\u001b[39m\u001b[0m\u001b[2m:24:40)\u001b[22m\u001b[2m\u001b[22m\n","name":"/Users/g/Developer/with-jest-app/stories/Button.test.tsx","startTime":1696959142807,"status":"failed","summary":""}],"wasInterrupted":false}
```
